### ISSUE TITLE
openlinkmap.org is down

### ISSUE THREAD

**Issue by cweiske** [rurseekatze/OpenLinkMap#40]
The site is down since ~ a week.

http://openlinkmap.org/

> Error 523 Ray ID: 27ddbd5513202d83 • 2016-03-03 14:22:19 UTC
> Origin is unreachable

**Comment by rurseekatze** [comment]
I stopped the project two months ago: https://lists.openstreetmap.org/pipermail/talk/2016-January/075420.html

The project is now continued by another person. Currently there seems to be a wrong configuration of the domain, so http://openlinkmap.org/ does not work. If you use http://www.openlinkmap.org/ instead, it works. I reported that problem already some days before, but it does not seem to be fixed yet.
