### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [rurseekatze/OpenLinkMap#41]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project [seems to be using osmosis](https://github.com/rurseekatze/OpenLinkMap/search?q=%22http%3A%2F%2Fplanet.openstreetmap.org%22+osmosis), which [will not follow redirects by default](https://trac.openstreetmap.org/ticket/5483).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https? All services respond over https and will start redirecting soon.

**Comment by rurseekatze** [comment]
I shut down the project in January 2016 and do not maintain it any more: https://lists.openstreetmap.org/pipermail/talk/2016-January/075420.html.

I transfered the domain to another person who had the plan to continue the website, but the project seems to be dead. The website does not show any data and the person does not answer my mails.
